# Generated by Django 5.1.3 on 2024-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0002_alter_adminprofile_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='rules',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='step_bid',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='images',
            field=models.ImageField(upload_to='auctionsite/lots_image'),
        ),
    ]
