# Generated by Django 5.1.3 on 2024-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0004_lot_user_name_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='auction_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
