# Generated by Django 5.1.3 on 2024-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0007_rename_price_after_auction_auctionhistory_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='current_price',
            new_name='start_price',
        ),
        migrations.AlterField(
            model_name='lot',
            name='user_name_bid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
