# Generated by Django 5.1.3 on 2024-11-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0008_rename_current_price_lot_start_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='user_name_bid',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user_name_bid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
