# Generated by Django 5.1.3 on 2024-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0009_remove_lot_user_name_bid_adminprofile_user_name_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
