# Generated by Django 5.1.3 on 2024-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0010_alter_adminprofile_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
