# Generated by Django 5.1.3 on 2024-11-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0011_alter_adminprofile_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='document_type_choice',
        ),
    ]
