# Generated by Django 5.1.3 on 2024-11-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0013_lot_creator_alter_userprofile_access_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User'},
        ),
    ]
