# Generated by Django 5.1.3 on 2024-11-11 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0015_alter_userprofile_options_alter_auctionhistory_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pay_counts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.userprofile'),
        ),
    ]
