# Generated by Django 5.1.3 on 2024-11-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0016_userprofile_pay_counts_alter_ban_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='start_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
